name: dartlane
description: Dartlane command line interface.
version: 0.1.0-dev.1
homepage: https://dartlane.aioncw.com/
repository: https://github.com/AbhijithKonnayil/dartlane/tree/dev/packages/dartlane
issue_tracker: https://github.com/AbhijithKonnayil/dartlane/issues
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  dartlane_core: ^0.1.0-dev.1
  http: ^1.6.0
  path: ^1.9.1
  pub_semver: ^2.2.1
  yaml: ^3.1.4

dev_dependencies:
  test: ^1.25.0
executables:
  dartlane:
