name: dartlane
description: Dartlane command line interface.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  args: ^2.7.0
  dartlane_core: any
  path: ^1.9.1
  yaml: ^3.1.4

dev_dependencies:
  test: ^1.25.0
executables:
  dartlane:
