analyzer:
  errors:
    cascade_invocations: ignore
    constant_identifier_names: ignore
    overridden_fields: ignore
include: package:very_good_analysis/analysis_options.6.0.0.yaml
linter:
  rules:
    public_member_api_docs: false
    always_specify_types: false
