name: dartlane
description: A Dart-powered CLI tool to define, manage, and run tasks (lanes) with speed and flexibility, inspired by Fastlane.
version: 0.0.1
publish_to: none
homepage: https://github.com/AbhijithKonnayil/dartlane/#/
repository: https://github.com/AbhijithKonnayil/dartlane
issue_tracker: https://github.com/AbhijithKonnayil/dartlane/issues

environment:
  sdk: ^3.5.0

dependencies:
  dartlane_core:
    path: ./packages/dartlane_core
  args: ^2.5.0
  change_case: ^2.2.0
  cli_completion: ^0.5.1
  io: ^1.0.5
  logger: ^2.5.0
  mason_logger: ^0.3.0
  meta: ^1.16.0
  pub_updater: ^0.4.0
  resource_portable: ^3.1.0

dev_dependencies:
  build_runner: ^2.4.12
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8
  very_good_analysis: ^6.0.0

executables:
  dartlane:
