// GENERATED CODE - DO NOT MODIFY BY HAND.
// Edit the files in templates/ and run `dart run melos run generate`.

/// The files `dartlane init` creates, as Dart string constants.
///
/// Generated from the files in `templates/`.
abstract final class Templates {
  /// `dartlane/pubspec.yaml`. Placeholders: `package_name`, `app_name`, `version`.
  static const pubspec = r'''
name: {{package_name}}
description: Dartlane lanes for {{app_name}}.
publish_to: none

environment:
  sdk: ^3.10.0

dependencies:
  dartlane_core: ^{{version}}
  dartlane_flutter: ^{{version}}
''';

  /// `dartlane/lanes.dart`.
  static const lanes = r'''
import 'package:dartlane_core/dartlane_core.dart';
import 'package:dartlane_flutter/dartlane_flutter.dart';

import 'config.dart';

/// Run a lane from the project root:
///
///     dartlane run build
///
/// or without the dartlane command:
///
///     dart run dartlane/lanes.dart build
Future<void> main(List<String> args) => dartlane(
  args,
  lanes: {
    'build': Lane('Build a release APK', (ctx) async {
      final build = await ctx.run(
        FlutterBuild.apk(
          flavor: Config.flavor,
          dartDefines: Config.dartDefines,
        ),
      );

      ctx.logger.success('Built ${build.path}');
    }),
    // Add your own lanes here.
  },
);
''';

  /// `dartlane/config.dart`.
  static const config = r'''
/// Settings used by the lanes in `lanes.dart`. Edit them for your project.
abstract final class Config {
  /// The flavor to build, or null if the app has no flavors.
  static const String? flavor = null;

  /// Compile-time values, each written KEY=VALUE, for example `ENV=prod`.
  static const List<String> dartDefines = [];
}
''';

  /// `dartlane/pubspec_overrides.yaml`, only for developing Dartlane itself. Placeholder: `repo`.
  static const overrides = r'''
# Generated by `dartlane init --local-repo`. Do not commit.
dependency_overrides:
  dartlane_core:
    path: {{repo}}/packages/dartlane_core
  dartlane_flutter:
    path: {{repo}}/packages/dartlane_flutter
''';
}
