name: dartlane_firebase
description: Firebase App Distribution action for Dartlane.
version: 0.0.1
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  dartlane_core: any
  http: ^1.6.0
  path: ^1.9.1

dev_dependencies:
  test: ^1.25.0
